### ISSUE TITLE
FOREMAN_HOME environment variable

### ISSUE THREAD

**Issue by ddavness** [rojo-rbx/foreman#17]
**I want the `.foreman` folder to be somewhere else rather than my user home folder.**

Is it possible to have foreman listening to an environment variable as to where placing it's `.foreman` folder?

**Comment by LPGhatguy** [comment]
Seems reasonable to me!

Why do you want to move where Foreman will install binaries, and where?

**Comment by ddavness** [comment]
Self-contained installations.

I'm currently writing an installation manifest for [Scoop](https://scoop.sh), which is a CLI installer for Windows. However, part of the philosophy of a manifest is keeping all files within a given container as possible.

Scoop has got a feature (persisting) that can carry configuration files and other useful stuff (in this case the binaries) across versions of the same application/package.

On the other hand, the user might want to get rid of that folder when uninstalling. For that, he would type `scoop uninstall -p foreman`. If we're able to contain the installation within one directory, managing it becomes easier. (And I won't need to write scripts to make up for that).

In this case, `~\.foreman` would be moved to `~\scoop\apps\foreman\current\home` or `~\scoop\apps\foreman\current\.foreman`
