### ISSUE TITLE
Foreman mistakenly considered a virus by McAfee

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/foreman#22]
After installing remodel, McAfee apparently warned me that foreman's executable was a virus. I installed foreman via cargo.

I think this is incorrect as there's no trace of malicious code in foreman...

![image](https://user-images.githubusercontent.com/48777426/86537758-59489900-bea6-11ea-89e2-3a0d5903c644.png)

**Comment by LPGhatguy** [comment]
I'm not sure there's anything we can do about McAfee detecting something like Foreman as a virus. We could try to submit it as a false-positive. I would also recommend dropping McAfee in favor of the built-in Windows Defender.

To be fair to antivirus software, the point of Foreman is to download more executables from the internet and run them. That's pretty sketchy!
