### ISSUE TITLE
zsh: command not found: rojo

### ISSUE THREAD

**Issue by JesterXL** [rojo-rbx/foreman#24]
Got a new Mac with the M1 processor. Successfully installed `foreman` and did `forman install` and it seemed to work installing Rojo. However, if I then run `rojo`, I get:
```shell
zsh: command not found: rojo
```

Not sure why it's not picking it up; if I look in the foreman/tools folder in home, I can see she did install it. Any hints?

**Comment by MayGo** [comment]
same here, any way to fix this or debug?

**Comment by LPGhatguy** [comment]
Do you have `~/.foreman/bin` added to your PATH? You'll need to restart your shell after doing so, too.

This isn't zsh specific.

**Comment by MayGo** [comment]
Yep, not zsh specific.

Thanks for pointing that out. I was indeed missing it from PATH.
I added it to ~/.bash_profile
`export PATH="/usr/local/bin:$HOME/.yarn/bin:~/.foreman/bin:$PATH"`
Now it works.

**Comment by oltrep** [comment]
I'll close this as it has been resolved and that we'll track improvements regarding that in #28
