### ISSUE TITLE
Foreman release v1.0.3 doesn't have binaries included

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/foreman#35]
The very recent `v1.0.3` foreman release doesn't include binaries, which breaks any CI scripts that make use of foreman releases.

![image](https://user-images.githubusercontent.com/26460940/148614760-6bcc5709-5dce-48b3-8d21-9ada427fa76b.png)
![image](https://user-images.githubusercontent.com/26460940/148614775-8cdd7c6b-e1c9-47e4-8029-7800a30de78b.png)

**Comment by oltrep** [comment]
The release was just created and that triggers a jobs that builds the binaries. Then, we take those and attach them to the release so it should be resolved in just a few minutes 😄

**Comment by NobleDraconian** [comment]
It might be a better idea to create a *draft* release, and then attach the binaries to the draft. That way, when the release is actually published, things that rely on them downstream don't break!

**Comment by matthargett** [comment]
Great idea, thanks for helping up improve the tool release process! :D
