### ISSUE TITLE
Release v1.0.3 Creates Broken Tools

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/foreman#36]
#30 moved the structopt initialization logic above the tool detection code, which means that Foreman now eats all command line arguments for the tools it tries to installs. As such, it doesn't work anymore at all!

This line can't be the first thing that runs:
https://github.com/Roblox/foreman/blob/4e3dbae8231ac6ba4a011471a78df616036a99b9/src/main.rs#L42

**Comment by matthargett** [comment]
Yup, looks like there's some missing code coverage here. Thanks for the quick report!
