### ISSUE TITLE
Foreman wally command not working

### ISSUE THREAD

**Issue by devtyp** [rojo-rbx/foreman#57]
For some reason, I have foreman installed, but the 'wally' command does not seem to work. Any ideas on how to fix this?

**Comment by oltrep** [comment]
Hello 👋 Make sure you've follow the steps to add the foreman `bin` directory to your PATH: https://github.com/Roblox/foreman#path-configuration

If that is done and it is still not working, then you just need to add wally to a configuration file and run foreman from that directory 🙂

**Comment by devtyp** [comment]
how do I add wally to the configuration file
