### ISSUE TITLE
Foreman tools wont work.

### ISSUE THREAD

**Issue by L3G5ND** [rojo-rbx/foreman#58]
None of the tools I've installed work. Foreman runs perfectly fine. When I run `foreman list`, all of the tools show up. However when I type something like `rojo --version`, I get this error 
```
rojo : The term 'rojo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ rojo
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (rojo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

#

**forman.toml:** 
```
[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
selene = { source = "Kampfkarren/selene", version = "0.21.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.14.3" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
```
**foreman list:** 
```
Installed tools:
  rojo-rbx/rojo
    - 7.2.1
  JohnnyMorganz/StyLua
    - 0.14.3
  Kampfkarren/selene
    - 0.21.1
  UpliftGames/wally
    - 0.3.1
```
**Version:** 1.0.5
**Installation method:** Rust
**What I've done:** Reinstalled Foreman, checked to make sure the path variable was correct, and reinstalled the tools many times.

**Comment by oltrep** [comment]
Hello 👋 Did you add the directory where foreman puts the downloaded binaries to your PATH variable? You can find some info on that in the [README](https://github.com/Roblox/foreman#path-configuration)

**Comment by L3G5ND** [comment]
I'm assuming your talking about adding the bin to the environment. In that case, yes, I have added it.
![image](https://user-images.githubusercontent.com/100112855/191580630-bf086751-e9d7-4800-8f3c-505ff49bc35f.png)

**Comment by L3G5ND** [comment]
Update: It appears that the bin executables are broken. When I run the executable for the specific tool in the tools directory, it works fine.
![image](https://user-images.githubusercontent.com/100112855/191581490-be6ab883-f848-4842-817e-525a7139cc14.png)

**Comment by L3G5ND** [comment]
Found the fix. The environment variable must be under User variables instead of System variables.
![image](https://user-images.githubusercontent.com/100112855/191617988-14137be1-f362-41be-8053-ae14a2fe27c9.png)
![image](https://user-images.githubusercontent.com/100112855/191618081-003d8e2f-a0d2-4dfb-aad3-c6d66bc5ae75.png)
