### ISSUE TITLE
Update cargo crate, latest one is 1.1.0

### ISSUE THREAD

**Issue by misl** [rojo-rbx/foreman#85]
Latest foreman release at the time of writing in 1.3.0. However 'cargo install foreman' still installs version 1.1.0. Looking at the crates the latest one available is still 1.1.0.

![image](https://github.com/Roblox/foreman/assets/2040396/bdad8e6b-75b7-4371-9fbe-f508beb26c3a)

Can the foreman crates be updated?

**Comment by ZoteTheMighty** [comment]
Thanks for filing this! I'll publish the latest releases.

**Comment by ZoteTheMighty** [comment]
Done!
